apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-e1-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaydheshiv/devops-e1
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ride-share
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
