apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching
  namespace: ride-share
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
        - name: matching
          image: ghcr.io/jaydheshiv/devops-e1/matching-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: matching
  namespace: ride-share
spec:
  selector:
    app: matching
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
